AllCops:
  Exclude:
    - 'vendor/**/*'
  DisplayCopNames: true

Rails:
  Enabled: true

require:
 - ./lib/balse.rb
 - rubocop-rspec
 - some-unpermitted-plugin

inherit_from:
 - https://gist.githubusercontent.com/vexus2/97c3a5af89887c024a24/raw/712610ac7659018c42235e179cd43793f9d1f516/rubocop.yml
 - .rubocop2.yml

Style/MethodName:
  Enabled: false

Style/ModuleFunction:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Style/MultilineBlockLayout:
  Enabled: false

Style/MultilineIfThen:
  Enabled: false

Style/MultilineOperationIndentation:
  Enabled: false

Style/MultilineTernaryOperator:
  Enabled: false

Style/NegatedIf:
  Enabled: false

Style/NegatedWhile:
  Enabled: false

Style/NestedTernaryOperator:
  Enabled: false

Style/Next:
  Enabled: false

Style/NilComparison:
  Enabled: false

Style/NonNilCheck:
  Enabled: false

Style/Not:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/OneLineConditional:
  Enabled: false

Style/OpMethod:
  Enabled: false

Style/ParenthesesAroundCondition:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Style/PercentQLiterals:
  Enabled: false

Style/PerlBackrefs:
  Enabled: false

Style/PredicateName:
  Enabled: false

Style/Proc:
  Enabled: false

Style/RaiseArgs:
  Enabled: false

Style/RedundantBegin:
  Enabled: false

Style/RedundantException:
  Enabled: false

Style/RedundantReturn:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/RescueModifier:
  Enabled: false

Style/SelfAssignment:
  Enabled: false

Style/Semicolon:
  Enabled: false

Style/SignalException:
  Enabled: false

Style/SingleLineBlockParams:
  Enabled: false

Style/SingleLineMethods:
  Enabled: false

Style/SingleSpaceBeforeFirstArg:
  Enabled: false

Style/SpaceAfterColon:
  Enabled: false

Style/SpaceAfterComma:
  Enabled: false

Style/SpaceAfterControlKeyword:
  Enabled: false

Style/SpaceAfterMethodName:
  Enabled: false

Style/SpaceAfterNot:
  Enabled: false

Style/SpaceAfterSemicolon:
  Enabled: false

Style/SpaceBeforeBlockBraces:
  Enabled: false

Style/SpaceBeforeComma:
  Enabled: false

Style/SpaceBeforeComment:
  Enabled: false

Style/SpaceBeforeSemicolon:
  Enabled: false

Style/SpaceInsideBlockBraces:
  Enabled: false

Style/SpaceAroundBlockParameters:
  Enabled: false

Style/SpaceAroundEqualsInParameterDefault:
  Enabled: false

Style/SpaceAroundOperators:
  Enabled: false

Style/SpaceBeforeModifierKeyword:
  Enabled: false

Style/SpaceInsideBrackets:
  Enabled: false

Style/SpaceInsideHashLiteralBraces:
  Enabled: false

Style/SpaceInsideParens:
  Enabled: false

Style/SpaceInsideRangeLiteral:
  Enabled: false

Style/SpecialGlobalVars:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/StringLiteralsInInterpolation:
  Enabled: false

Style/StructInheritance:
  Enabled: false

Style/SymbolLiteral:
  Enabled: false

Style/SymbolProc:
  Enabled: false

Style/Tab:
  Enabled: false

Style/TrailingBlankLines:
  Enabled: false

Style/TrailingComma:
  Enabled: false

Style/TrailingWhitespac:
  Enabled: false

Style/TrivialAccessors:
  Enabled: false

Style/UnlessElse:
  Enabled: false

Style/UnneededCapitalW:
  Enabled: false

Style/UnneededPercentQ:
  Enabled: false

Style/UnneededPercentX:
  Enabled: false

Style/VariableInterpolation:
  Enabled: false

Style/VariableName:
  Enabled: false

Style/WhenThen:
  Enabled: false

Style/WhileUntilDo:
  Enabled: false

Style/WhileUntilModifier:
  Enabled: false

Style/WordArray:
  Enabled: false

Style/AccessModifierIndentation:
  Enabled: false

Style/AccessorMethodName:
  Enabled: false
